# Generated by Django 5.1 on 2024-08-21 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('turma', '0002_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateTimeField()),
                ('descricao', models.TextField()),
                ('local', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('ES', 'Espera'), ('AC', 'Aceito'), ('CA', 'Cancelado'), ('RE', 'Realizado')], default='ES', max_length=20)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='user.aluno')),
                ('turma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='turma.turma')),
            ],
        ),
    ]
