# Generated by Django 5.1 on 2024-08-20 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('turma', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.orientador', verbose_name='Autor da turma'),
        ),
    ]
