# Generated by Django 5.1 on 2024-08-21 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comentario', '0001_initial'),
        ('planoEstudo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='plano_de_estudo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='planoEstudo.planodeestudo'),
        ),
    ]
